### PR TITLE
For Windows Too

### PR DESCRIPTION
**Pull request by electriclief**
Your code worked like a charm for me....
Just fixed Os which/where issue.

(And added windows install not for mpg123)

Respect to the Author - Loved your code

Lief.
https://www.npmjs.com/package/liefs-layout-manager

### CODE REVIEW

**Comment by pawurb** [comment]
Thanks for the pr. Could you move detecting platform to `os.platform` method for consistency and handle windows specific message if mpg123 is missing on windows ? right now it would display linux message on windows.

btw i am not sure if the `navigator` variable would be available in all environments.

**Comment by electriclief** [comment]
Ok - I believe that did the trick.....

I would like to test this change.
I use a different build system.(I am not familiar with yours)
A) What is your build command so I can test it (Me do work for free)
B) No response means:Don't worry about it

**Comment by pawurb** [comment]
@electriclief after applying the changes you can test the new code by running `./bin/normit` from project directory. it will use the local code version then. Please let me know which systems you tested on. I can check if it works on mac os on my side.

one last code change, could you simplify assigning `osindex` ? nested ternary operators are bit difficult to comprehend. maybe sth like:
```
var osindex = null
if((osp.indexOf("win") === -1)){
  osindex = 0
else if(ops=='darwin'){
  2
} else ...
```

**Comment by electriclief** [comment]
---------------------------- ok I just learned this myself 
-------------------
 >where normit (Windows which)
C:\Users\lief\AppData\Roaming\npm\normit
C:\Users\lief\AppData\Roaming\npm\normit.cmd

type C:\Users\lief\AppData\Roaming\npm\normit.cmd        (Windows cat)
@IF EXIST "%~dp0\node.exe" (
   "%~dp0\node.exe"  "%~dp0\node_modules\normit\bin\normit" %*
) ELSE (
   @SETLOCAL
   @SET PATHEXT=%PATHEXT:;.JS;=;%
   node  "%~dp0\node_modules\normit\bin\normit" %*
)
---------------------- npm creates this cmd file -> build is really 
"node normit"
(Which is what you were trying to tell me)

Fixing as per your request
Working on "proof" of working changes for multiple os.
Will respond again today with said proof.

No response necessary,

Lief

**Comment by electriclief** [comment]
ok
works fine in windows proof https://www.youtube.com/watch?v=PjBarbs5L24

works fine in Ubuntu proof https://www.youtube.com/watch?v=oGTHjgc8Kbg

I haven't made a mac virtualbox, so out of luck there

Cheers

Networking for work.

**Comment by pawurb** [comment]
@electriclief published a new package, please download and confirm works on both ubuntu and windows

**Pull request merged**
